### ISSUE TITLE
Request for Data Processing Code

### ISSUE THREAD

**Issue by ltzheng** [LatentActionPretraining/LAPA#1]
Thanks for open-sourcing this great work! Could you please provide the code or instructions on preprocessing OXE, Something-Something V2, and Bridge V2 datasets (i.e., how to obtain the jsonl files from the raw datasets)? Currently there is only a jsonl file for the OXE dataset, and there seems to be no instruction for latent action quantization to obtain the 'delta' in the dataset.

**Comment by Mcccccc1024** [comment]
Have you obtained how to convert the jsonl files now?

**Comment by joeljang** [comment]
Thank you for your interest in LAPA! We currently do not have a set timeline of when we are going to release the code for our stage 1 pipeline (latent action quantization stage). Hopefully in the upcoming weeks!
