### ISSUE TITLE
Add method or example for continuous prediction

### ISSUE THREAD

**Issue by jmwang0117** [LatentActionPretraining/LAPA#15]
Thank you for your excellent work. 

You mentioned that predicting 4 actions continuously is more effective than predicting 1 action at a time. Could you please provide code or an example demonstrating how to predict 4 actions continuously? 

I'd appreciate this clarification because I noticed that fine-tuning on SIMPLER rollout trajectories (100 trajectories) only predicts one action at a time. 

Thank you!

**Comment by seonghyeonye** [comment]
Thank you for the comment.
Could you clarify the part of `predicting 4 actions continuously is more effective than predicting 1 action at a time.`?

All of our policy models predict single discrete set of actions at a time. (ex) If the target embodiment is 7 DoF, we predict 7 discrete tokens for action)

**Comment by jmwang0117** [comment]
Thank you for your detailed response.

What I wanted to ask is how to accurately predict the actions for the next 4 time steps based on the current image and command, where each action is represented by 7 degrees of freedom (7 DoF). I noticed that single-step prediction often results in timing inaccuracies. For example, if the desired behavior requires the gripper to close over the next 4 moments, single-step predictions can **oscillate unrealistically**—such as predicting **"open, close, open, close"**—instead of **smoothly progressing toward "close."**
