### ISSUE TITLE
Question about get_averaged_values()

### ISSUE THREAD

**Issue by PPjmchen** [LatentActionPretraining/LAPA#7]
Thank you for your excellent work!

I am trying to fine-tune and deploy LAPA on my own data, and I have trouble converting the latent actions into real ones. 

In the following code https://github.com/LatentActionPretraining/LAPA/blob/9b743364912e4f00efbdacaa959086b1524fe530/latent_pretraining/deploy.py#L125-L136, the `indices` seems to be a latent action predicted by the LAPA model, in my experiment, it's an `array([[0, 1, 2, 0]], dtype=int32)` in the first step. 

However, in my case the `self.action_scale_list` cannot be indexed with a indices like `array([[0, 1, 2, 0]], dtype=int32)`. The shape of the  `self.action_scale_list` is attached below, it's extracted by the `finetune_preprocess.py`. 
![image](https://github.com/user-attachments/assets/870b0c33-d4ba-4be5-ad18-edf261c7a888)

So what's the meaning of the `row_idx` and `idx`? Is the prediction like `array([[0, 1, 2, 0]], dtype=int32)` a correct output? And is my  `self.action_scale_list` valid?

**Comment by bighuang624** [comment]
@PPjmchen Hi, I am not the author of this article, and I am not sure if your question has been resolved. But perhaps we can discuss it. In my reproduction, `len (indices)==7`, e.g., [37, 225, 52, 237, 192, 221, 1], as the indices is from [predict_action function](https://github.com/LatentActionPretraining/LAPA/blob/9b743364912e4f00efbdacaa959086b1524fe530/latent_pretraining/deploy.py#L110).

**Comment by bighuang624** [comment]
@PPjmchen I am now able to run the fine-tuning and inference processes, but the results are much lower than what they reported  (both LAPA and Scratch). I am still searching for the reason.

**Comment by seonghyeonye** [comment]
The indices should be a 7 dof action, instead of latent action when fine-tuning. Note that LAPA model is finetuned on ground-truth action trajectories after it has been pretrained to predict latent actions. Let us know or open an issue if there are issues when replicating the results!
