### ISSUE TITLE
Latent action sequence variable length 

### ISSUE THREAD

**Issue by brunomachado37** [LatentActionPretraining/LAPA#9]
First of all, congratulations on the great open-source work!

I have a question regarding the latent action quantization stage.

Given that the output of the cViViT will have one token for each patch in the input, how do you obtain a latent action sequence of variable lengths? Do you perform some concatenation or aggregation of those tokens before the quantization? 

Thanks in advance!

**Comment by joeljang** [comment]
So we use CNN layers to get the dimension that we want. So we first choose the sequence length that we ultimately want, and do convolution to match the dimensions. Some examples are provided in this line: https://github.com/LatentActionPretraining/LAPA/blob/00a94bfdfb09d9ee0ccb0f68545a47fef5cb2097/laq/laq_model/nsvq.py#L56
